<?php  include VIEW.'header.phtml' ?>
<div class="col-md-3"></div>
<div class="d-flex justify-content-center h-100 center-block col-md-6 ">
    <div class="user_card">
        <div class="d-flex justify-content-center">
            <div class="brand_logo_container">
                <img src="/images/defultLogin.jpeg" class="brand_logo" alt="Logo">
            </div>
        </div>
        <div class="d-flex justify-content-center form_container">
            <form  role="form" method="post"  action="/home/postLogin">


            <div class="input-group mb-3 ">
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fa fa-envelope"></i></span>
                </div>
                <input type="text" name="username" class="form-control input_user " value=""
                       placeholder="username">
            </div>

            <div class="input-group mb-2">
                <div class="input-group-append">
                    <span class="input-group-text"><i class="fa fa-key"></i></span>
                </div>
                <input type="password" name="password" class="form-control input_pass" value=""
                       placeholder="password">
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="customControlInline">
                    <label class="custom-control-label" for="customControlInline">تذكرني </label>
                </div>
            </div>
            <div class="d-flex justify-content-center mt-3 login_container">
                <input type="submit" name="submit" class="btn login_btn"/>
            </div>
            </form>
        </div>

        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                هل بديك حساب من قبل ؟ <a href="home/register" class="ml-2">التسجيل بالموقع</a>
            </div>
            <div class="d-flex justify-content-center links">
                <a href="#">هل نسيمت كلمة السر</a>
            </div>
        </div>
    </div>
</div>

<?php  include VIEW.'footer.phtml' ?>
