</head>
<body class="nav-md">
<div class="container body">
    <div class="main_container">

        <!-- menu start -->
        <?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'menu.php' ?>
        <!-- menu end -->
        <!-- top navigation -->
        <?php include VIEW . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'topNavigation.blade.php' ?>


        <!-- /top navigation -->
        <!-- /header content -->

        <!-- page content -->

        <div class="right_col" role="main">
            <?php echo Message::check('main'); ?>
