<!DOCTYPE html>
<html style="direction: rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo(isset($this->pageTitle) ? $this->pageTitle : 'page n'); ?> </title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta name="fontiran.com:license" content="Y68A9">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Bootstrap -->
    <link href="/design/admin/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/design/admin/bootstrap-rtl/dist/css/bootstrap-rtl.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/design/admin/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/design/admin/nprogress/nprogress.css" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="/design/admin/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="/design/admin/iCheck/skins/flat/green.css" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="/design/admin/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <link href="/design/admin/google-code-prettify/bin/prettify.min.css" rel="stylesheet">

    <!-- Select2 -->
    <link href="/design/admin/select2/dist/css/select2.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/design/admin/select2-bootstrap4-theme/select2-bootstrap4.min.css">

    <!-- Switchery -->
    <link href="/design/admin/switchery/dist/switchery.min.css" rel="stylesheet">
    <!-- starrr -->
    <link href="/design/admin/starrr/dist/starrr.css" rel="stylesheet">
    <link rel="stylesheet" href="/design/admin/jquery-ui/jquery-ui.css">


    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

    <!-- Custom Theme Style -->
    <link href="/design/admin/build/css/custom.min.css" rel="stylesheet">
